# Generated by Django 6.0.6 on 2026-07-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='music_cue',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='music_playing',
        ),
    ]
