# Generated by Django 6.0.6 on 2026-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_question_clip_remove_quiz_music_cue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interlude_title',
            field=models.CharField(blank=True, help_text='Shown on the projector during the speech before this question.', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='interlude_image',
            field=models.ImageField(blank=True, help_text='Shown on the projector below the interlude title.', upload_to='interludes/'),
        ),
    ]
