# Generated by Django 6.0.6 on 2026-07-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_interlude_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Mand'), ('f', 'Kvinde'), ('x', 'Andet')], max_length=1),
        ),
        migrations.AddField(
            model_name='player',
            name='kids',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='relation',
            field=models.CharField(blank=True, choices=[('family', 'Familie'), ('in_laws', 'Svigerfamilie'), ('friend', 'Ven'), ('colleague', 'Kollega'), ('other', 'Andet')], max_length=10),
        ),
    ]
