# Generated by Django 6.0.6 on 2026-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_age_player_gender_player_kids_player_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='relation',
            field=models.CharField(blank=True, choices=[('family', 'Familie'), ('friend', 'Ven'), ('badminton', 'Badminton')], max_length=10),
        ),
    ]
