# Generated by Django 6.0.6 on 2026-07-17 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_player_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DrinkyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2.99)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinky_readings', to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.drinkyround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'player'), name='one_reading_per_round')],
            },
        ),
    ]
