# Generated by Django 6.0.6 on 2026-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drinkyround_drinkyreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Mand'), ('f', 'Kvinde')], max_length=1),
        ),
    ]
