# Generated by Django 6.0.6 on 2026-07-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkyround',
            name='title',
            field=models.CharField(blank=True, help_text="Optional label shown instead of the round number, e.g. a time like '15.00'.", max_length=50),
        ),
    ]
