# Generated by Django 6.0.6 on 2026-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_drinkyround_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='relation',
            field=models.CharField(blank=True, choices=[('family', 'Familie'), ('friend', 'Ven'), ('badminton', 'Grindsted')], max_length=10),
        ),
    ]
